name: dart_remarkable_api
description: reMarkable client API implemented in pure dart.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.12.2
  uuid: ^2.2.2
  archive: ^2.0.13

dev_dependencies:
  test: ^1.15.7

flutter:
